### ISSUE TITLE
Icons resetting when moving in and out of a folder

### ISSUE THREAD

**Issue by Poshy163** [TimeBlaster/LeagueDeck#15]
When entering or exiting a folder, the icons reset to no champ or summoner, then fail to reset back to normal

**Comment by TimeBlaster** [comment]
This is fixed in the upcoming version.

**Comment by Poshy163** [comment]
Any update on a release timeline for it?

**Comment by istefanou** [comment]
Is there any update on this?

**Comment by camrentm** [comment]
> This is fixed in the upcoming version.

Is this project dead? Really cool concept but the folder issue really makes it difficult to use realistically

**Comment by L1cardo** [comment]
Hi, any fix for this?
