### ISSUE TITLE
Chat Messages not working properly

### ISSUE THREAD

**Issue by TimeBlaster** [TimeBlaster/LeagueDeck#2]
Riot has reworked the chat in 10.24 and my automatic inputs stopped working.
SendChatMessage method executes properly. Might have to adjust timings.

**Comment by Louis-PAGNIER** [comment]
Same problem

**Comment by AlanAltonchi** [comment]
I checked the code and you are sending KeyDown without KeyUp.

You're basically holding down Enter after sending the message in chat & Enter keeps being held down which is why you can't press the Elgato keys to send a new message.

Make sure to add KeyUp after your KeyDown.

**Comment by TimeBlaster** [comment]
The InputSimulator used here sends both the KeyDown and a KeyUp, but the method name could have been better, I agree.
I have tried using the Win32API directly but I run into the same issues with League's chat system. 
Atleast this library takes care of different keyboard layouts.
I am currently preparing an update with a new feature and some other bug fixes, but this I can't fix.
If you have any other suggestions or ideas, I am happy to try them.

**Comment by AlanAltonchi** [comment]
> The InputSimulator used here sends both the KeyDown and a KeyUp, but the method name could have been better, I agree.
> I have tried using the Win32API directly but I run into the same issues with League's chat system.
> Atleast this library takes care of different keyboard layouts.
> I am currently preparing an update with a new feature and some other bug fixes, but this I can't fix.
> If you have any other suggestions or ideas, I am happy to try them.
> 
> **EDIT:**
> I checked it again and you were right, I thought I was using the KeyPress method, but I wasn't.
> Will be fixed with new release.

Glad you got it working.
